services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    #healthcheck:
     # test: ["CMD-SHELL", "pg_isready -U taskflow -d taskflow"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
